### ISSUE TITLE
Passing value between slick

### ISSUE THREAD

**Issue by shrijan** [vasyabigi/angular-slick#110]
Hi,

I got 2 slick carousel going in a page.

Currently when there is swipe in first slick(onafterchange) ng-repeat in 2 slick needs to change.

I have been playing with it from last 2 days with any success.

Any help appreciated.

Thanks

**Comment by Graham42** [comment]
If you found a solution to your problem it would be useful to post it so other people in the future can learn from it.

**Comment by shrijan** [comment]
I havent found solution

http://stackoverflow.com/questions/31108573/angular-slick-transclude-not-working-in-dynamic-ng-repeat
