### ISSUE TITLE
Responsive by default

### ISSUE THREAD

**Issue by ttbarnes** [vasyabigi/angular-slick#116]
I'm having a nightmare configuring `angular-slick` to work nicely on smaller screen sizes. I'm not the only one.

The main reason is because each item gains a width, for example `225280px` and therefore destroys 'mobile friendliness'.

I've tried several approaches suggested in the docs, SO questions, github issues - nothing seems to work, so i'm going to use something else instead now.

I think the slider should 'just work' on mobiles. I imagine that the majority of users will be supporting mobile. In other words, it's probably an edge case to have a non-responsive slider.

Maybe this should be suggested in slick rather than angular-slick (?).

**Comment by idreeshaddad** [comment]
Yes, you are right. Angular-slick is just an angular wrapper for slick. This issue is better opened on slick repo.

**Comment by ttbarnes** [comment]
Opend in slick repo: https://github.com/kenwheeler/slick/issues/1588
