### ISSUE TITLE
ng-repeat does not work

### ISSUE THREAD

**Issue by kadkaz** [vasyabigi/angular-slick#2]
$(element).document.ready() is executing earlier than ng-repeat is doing the logic. (possible when async loading collection). please use $timeout for this as solution,

**Comment by jcsena** [comment]
@victorarandaiglesias  it's true! thks!

**Comment by aleksandrj1** [comment]
The site http://vasyabigi.github.io/angular-slick/
only shows (dot dot dot) it dosent say anything about repeat. I can add my own ng-repeat but I thought the carousel was supposed to implement that for us? Totally not clear :(

**Comment by kedartendolkar** [comment]
I didn't find how to use angular-slick with images until I searched for the issue and landed on this page.
Please provide full example in readme instead of
`````
<slick>
...
<slick>
`````

**Comment by bcruddy** [comment]
@daniel-obadia instead of setting `data` to your actual data set it to a another variable (I used dataLoaded) and then set that variable to `true` in the callback where your image data is set.
Controller:

```
StreamService.getStreamById($scope.stream.id, auth).success(function (stream) {
      $scope.photoStream = stream.Results.Photos;
      $scope.dataLoaded = true;
 });
```

View:

```
<slick slides-to-show="3" slides-to-scroll="1" init-onload="true" data="dataLoaded">
    <div ng-repeat="photo in photoStream"><img ng-src="{{photo.url}}" /></div>
</slick>
```

**Comment by jcsena** [comment]
<slick infinite="true" dots="true" arrows="true" data="photoStream" init-onload="true">
   <div ng-repeat="photo in photStream"> 
      <img ng-src="{{photo.image}}"alt="{{articleSlide.title}}" />
   </div>

</slick>

@daniel-obadia

**Comment by jcsena** [comment]
``` html
 <slick infinite="true" dots="true" arrows="true" data="photoStream" init-onload="true">
   <div ng-repeat="photo in photoStream"> 
      <img ng-src="{{photo.url}}"  />
   </div>
</slick>
```

@daniel-obadia

**Comment by amrfaisal** [comment]
Actually (init-onload="true") didn't work for me. The best way is to use (ng-if="dataArray.length").

**Comment by ClaudioMeinberg** [comment]
The correct way to implement it is including 
```
on-finish-render="init()"
```
in your repeat.

Check this:
https://github.com/kbdaitch/angular-slick-carousel#attributes

**Comment by nkrambo** [comment]
@amrfaisal Thanks! This worked to resolve my issue as well.

**Comment by rickplancess** [comment]
How to define the callback method inside slick tag. Eg,
<slick callback="">.....</slick>

**Comment by Pyohwan** [comment]
@bcruddy He is right!

**Comment by wonglok** [comment]
try to use  ng-if it works for me <3

``` html
<div ng-repeat="..." ng-if="array.legnth > 0">

</div>
```

**Comment by gnganapath** [comment]
Thanx.. It's working...

**Comment by sajumani** [comment]
Not working for me.... My Code 

> <slick

 infinite="true" dots="true" arrows="true" data="photoStream" init-onload="true" >

> <div

 ng-repeat="alldata in alldatas" ng-if="alldatas.length > 0" > 
      {{alldata}}
   </div>
</slick>

$timeout(function() {
    $scope.alldatas = [1,2];
}, 1000

**Comment by sajumani** [comment]
https://github.com/devmark/angular-slick-carousel    works fine...

**Comment by surendra329** [comment]
@njj njj  thank you for your directive on Jun 12, 2014

**Comment by wembernard** [comment]
Thanks for the workaround @njj. Problem is still here. 

For people who're still looking for answers, just change your:

```
<slick infinite="true" slides-to-show="3" slides-to-scroll="3" dots="true" arrows="true" init-onload="true" data="ctrl.users" responsive="ctrl.breakpoints">
    <div ng-repeat="user in ctrl.users track by $index">
        ...
    </div>
</slick>
```

into 

```
<div ng-if="ctrl.users && ctrl.ready">
    <slick infinite="true" slides-to-show="3" slides-to-scroll="3" dots="true" arrows="true" init-onload="true" data="ctrl.users" responsive="ctrl.breakpoints">
        <div ng-repeat="user in ctrl.users track by $index">
            ...
        </div>
    </slick>
</div>
```

and add in your Controller

```
      $timeout(function() {
        ctrl.ready = true;
      }, 1000);
```

This way, `slick` won't init (thanks to ng-if parent) until `users` are loaded and `ready` has `$timeout`.

**Comment by ppshein** [comment]
@amrfaisal Thanks! It's charming.

**Comment by pranay2419** [comment]
Thank You so much! It helped me a lot
