### ISSUE TITLE
Specify responsive?

### ISSUE THREAD

**Issue by seiyria** [vasyabigi/angular-slick#3]
How do you specify `responsive`? I've tried it as a `$scope` variable and straight in the directive and neither of them seem to work.

**Comment by aleksandrj1** [comment]
This worked for me -- didn't need to modify the directive:
<div slick 
init-onload="true" 
data="programs" 
arrows="true" 
currentindex="0" 
slides-to-scroll="1" 
slides-to-show="1" 
infinite="true" 
touch-move="true" 
speed="300" 
dots="false" 
responsive="[
                  {
                      breakpoint: 768,
                      settings: {
                          arrows: false,
                          dots: true
                      }
                  }
                ]">

**Comment by mohanuideveloper** [comment]
where to add this 

init-onload="true" 
data="programs" 
arrows="true" 
currentindex="0" 
slides-to-scroll="1" 
slides-to-show="1" 
infinite="true" 
touch-move="true" 
speed="300" 
dots="false" 
responsive="[
{
breakpoint: 768,
settings: {
arrows: false,
dots: true
}
}
]">

inside HTML or inside controller

**Comment by rahulvermaiitk** [comment]
Thanks a lot it worked for me quite good..!~!
