### ISSUE TITLE
Manually trigger slide using the slickToGo method

### ISSUE THREAD

**Issue by cwhite92** [vasyabigi/angular-slick#5]
Hi!

Great directive, however I'm running into a problem whereby I need to run a method on the plugin (slickGoTo in this case) and I'm not sure how to go about doing that.

Basically rather than using the arrows the plugin generates I've made my own buttons which should toggle between two slides. Take the following markup as an example:

```
<div ng-repeat="thing in someThings">
    <div class="portal-box font-gray">
        <slick dots="false" arrows="false" draggable="true" infinite="false" autoplay="false" speed="700" slides-to-show="1" swipe-move="false" slides-to-scroll="1">
            <div class="slide">
                <p>First slide content</p>
                <button>Go to next slide</button>
            </div>
            <div class="slide">
                <p>Second slide content>
                <button>Go to previous slide</button>
            </div>
        </slick>
    </div>
</div>
```

How would I make the two `<button>`'s contained within the slides toggle each slide?

Help is appreciated. :)

**Comment by younesouhbi** [comment]
The example given by vasyabigi above didn't work for me. I had to change the line 140 in the directive from:
`return slider.slickGoTo(newVal);`
to:
`return slider.slick("slickGoTo", newVal);`

**Comment by capsule5** [comment]
Hello. Nice directive but same problem. I need to change current slide from the controller. vasyabigi's solution doesn't work if current-index is a scope variable defined with a stateParam for example. slickGoTo is necessary!

**Comment by smongey** [comment]
I’m generating thumbnails using a separate ng-repeat outside of the slick element. This is so I can click a thumbnail and slick will go to the relevant slide. I’m using this

```
index=$index
```

within a separate ng-repeat for the thumbnails. It appears to generate the right code but will only work if this is static and not within the repeat. Any idea how this might be resolved or why this isnt working?

**Comment by veruscae** [comment]
Hallo! Great directive but I need to change current slide and have the same problem. the Example in app/views/main.html  doesn't work for me :(
I have multiple-items and dynamic load. 
Any help will be welcome.

**Comment by capsule5** [comment]
`<slick  current-index="slick.current"  on-after-change="slick.onAfterChange()" >
<div ng-repeat = "slide in slides" on-finish-render="slick.init();"></slick>`

and

`$scope.slick = {
    current:0,
    init : function(){},
    goto : function(index){this.current = index},
    next : function(index){this.current++},
    prev : function(index){this.current--},
    onBeforeChange : function(){}, 
    onAfterChange : function(){}
  }`

does the trick for me. Hope it helps.

**Comment by veruscae** [comment]
@capsule5 Thanks! That was really helpful! 
Finally it works :-)

**Comment by Lospepes** [comment]
Hello for me, I did exactly the opposit of @younesouhbi 
from:
return slider.slick("slickGoTo", newVal);
to:
return slider.slickGoTo(newVal);

Someone can explain to me why I needed to do that please ?
