### ISSUE TITLE
What is the recommended way to use custom arrows?

### ISSUE THREAD

**Issue by imdpk** [vasyabigi/angular-slick#55]
Here is a snippet of my code but for some reason it is not working.

angular.module('portfolioModule.controllers')
.controller('PortfolioController', ['$rootScope', '$scope', function($rootScope, $scope){
    $scope.prevArrow = '+';
    $scope.nextArrow = '+';
...
...
);

**Comment by alabels9** [comment]
Hi,
I had the same issue of not knowing how to get my custom arrows in.  Finally I figured it out.  To my understanding, if you are using custom arrows (I was using web fonts to make the arrows) then you just need to pass a class defining the custom arrow into the prev-arrow and next-arrow attributes.  In the example below I was using the .left and .right class.  I tried to do it similar to how you were doing it in your snippet, but I also could not get that to work, but the solution below works.  I hope this helps!

<slick slides-to-show=3 slides-to-scroll=1 next-arrow=".right" prev-arrow=".left">
     <div ng-repeat="slide in slides">
          <div> {{slide.text}} </div>
     </div>
</slick>

<a href="" class="left">
     <span class="icon-arrow-left"></span>
</a>

<a href="" class="right">
     <span class="icon-arrow-right"></span>
</a>

**Comment by borismihajlovic** [comment]
@alabels9 

Thank you, you are a god/goddes! I've been searching for the solution 2 days and this is the only solution that works (and it isn't mentioned anywhere else).

Thank you!

**Comment by SeyZ** [comment]
Thanks @alabels9 !

**Comment by DavidMMelin** [comment]
At least I only wasted an hour before finding this, thanks @alabels9 !

**Comment by pioku** [comment]
Works, thanks.

**Comment by imdpk** [comment]
This worked thanks!

**Comment by grothier** [comment]
Hi @alabels9 !
I don't get it: where I am supposed to access the <slick> HTML? I am using the slick gem on rails, and can't find this in order to add a custom image for arrows... Thanks!

**Comment by joeipe** [comment]
This worked for me. Thank you.
