### ISSUE TITLE
Autoplay not Working after Grunt Build Yeoman Angular App

### ISSUE THREAD

**Issue by deerawan** [vasyabigi/angular-slick#73]
## Steps to Reproduce
1) Create Yeoman Angular App (yo angular)
2) Install Angular Slick via Bower
3) Add some Slick HTML

```
<slick infinite=true slides-to-show=1 slides-to-scroll=1 autoplay=true>
  <div ng-repeat="i in [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]"><h3>{{ i }}</h3></div>
</slick>
```

4) Confirmed autoplay working on localhost:9000 (grunt serve mode)
5) Grunt build
6) Slick autoplay not working for dist mode

There is no error message on console.

**Comment by deerawan** [comment]
Fixed!

I found the source of problem. It is caused by **HTML minifier collapseBooleanAttributes** option. The default setting of HTML minifier as shown below

```
// Gruntfile.js

htmlmin: {
      dist: {
        options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: true,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true
        },
        files: [{
          expand: true,
          cwd: '<%= yeoman.dist %>',
          src: ['*.html', 'views/{,*/}*.html'],
          dest: '<%= yeoman.dist %>'
        }]
      }
    },
```

You see that **collapseBooleanAttributes** is set to **true**. When you do Grunt build, HTML min will remove "true" value in attribute, so it become like below. 

```
<slick infinite=true slides-to-show=1 slides-to-scroll=1 autoplay>
  ....
</slick>
```

Slick autoplay will work only if the attribute match **autoplay=true**. 

The solution is just set **false** to **collapseBooleanAttributes**. The Final HTML min configuration 
```
// Gruntfile.js

htmlmin: {
      dist: {
        options: {
          collapseWhitespace: true,
          conservativeCollapse: true,
          collapseBooleanAttributes: false,
          removeCommentsFromCDATA: true,
          removeOptionalTags: true
        },
        files: [{
          expand: true,
          cwd: '<%= yeoman.dist %>',
          src: ['*.html', 'views/{,*/}*.html'],
          dest: '<%= yeoman.dist %>'
        }]
      }
    },
```

Thank you. I close this issue.

**Comment by cpBurn** [comment]
+1 for that. Thanks

**Comment by Wolfium** [comment]
+1 for the exact and simple workaound/solution.

**Comment by GianlucaBobbio** [comment]
Thanks!

**Comment by joelbowen** [comment]
+1

**Comment by vallieres** [comment]
+1 thanks!

**Comment by hccuneyt** [comment]
+1 Thanks!
Finally the solution, this was making me crazy.

**Comment by luispeerez** [comment]
Thanks a lot, as @hccuneyt I was getting crazy about this.
