### ISSUE TITLE
Need a button that allows me to go one slide to the right

### ISSUE THREAD

**Issue by billykeyss** [vasyabigi/angular-slick#99]
Hi, I am unsure of how to implement a button in the carousel itself that will take me one slide to the right or one slide to the left. Is there an option that will let me create my own custom button that will let a user scroll through the slides? Any help would be greatly appreciated.

EDIT: I think what I need to accomplish this is the prevArrow and nextArrow. Can anyone provide an example of how to use these?

**Comment by sujeetjaiswara** [comment]
Share your code on plunker

**Comment by billykeyss** [comment]
Figured it out. 

If anyone else is wondering, you have to define a class in your slide
  slick prev-arrow=".prev-slide" next-arrow=".next-slide"

and then in arrows:

button type="button" class="next-slide"></button
button type="button" class="prev-slide"></button

Thanks

**Comment by sujeetjaiswara** [comment]
Slick also provide style sheets you can customized those css according to you.
